// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionStock.Migrations
{
    [DbContext(typeof(StockContext))]
    [Migration("20230722214641_MigrationV1")]
    partial class MigrationV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestionStock.Models.Destocker", b =>
                {
                    b.Property<int>("IdDestock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<string>("NumBonSortie")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuantiteSortie")
                        .HasColumnType("int");

                    b.HasKey("IdDestock");

                    b.HasIndex("IdProduit");

                    b.HasIndex("NumBonSortie");

                    b.ToTable("Destockers");
                });

            modelBuilder.Entity("GestionStock.Models.Entree", b =>
                {
                    b.Property<string>("NumBonEntre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateEntree")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomFournisseur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NumBonEntre");

                    b.ToTable("Entrees");
                });

            modelBuilder.Entity("GestionStock.Models.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Img")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QuantiteStock")
                        .HasColumnType("int");

                    b.HasKey("IdProduit");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("GestionStock.Models.Sortie", b =>
                {
                    b.Property<string>("NumBonSortie")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateSortie")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NumBonSortie");

                    b.ToTable("Sorties");
                });

            modelBuilder.Entity("GestionStock.Models.Stocker", b =>
                {
                    b.Property<int>("IdStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<string>("NumBonEntre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuantiteEntree")
                        .HasColumnType("int");

                    b.HasKey("IdStock");

                    b.HasIndex("IdProduit");

                    b.HasIndex("NumBonEntre");

                    b.ToTable("Stockers");
                });

            modelBuilder.Entity("GestionStock.Models.Destocker", b =>
                {
                    b.HasOne("GestionStock.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionStock.Models.Sortie", "Sortie")
                        .WithMany("Destockers")
                        .HasForeignKey("NumBonSortie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Sortie");
                });

            modelBuilder.Entity("GestionStock.Models.Stocker", b =>
                {
                    b.HasOne("GestionStock.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionStock.Models.Entree", "Entree")
                        .WithMany("Stockers")
                        .HasForeignKey("NumBonEntre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entree");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("GestionStock.Models.Entree", b =>
                {
                    b.Navigation("Stockers");
                });

            modelBuilder.Entity("GestionStock.Models.Sortie", b =>
                {
                    b.Navigation("Destockers");
                });
#pragma warning restore 612, 618
        }
    }
}
